server:
  port: 8080
spring:
  application:
    name: account-service
  datasource:
    druid:
      url: jdbc:mysql://atm-mysql:3306/db_accounts?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 616437
      max-active: 20
      initial-size: 5
      min-idle: 5
  cloud:
    nacos:
      server-addr: atm-nacos:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-underline: true
