server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: atm-nacos:8848
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/**